#!/bin/sh

set -e

SCRIPTDIR=$(cd "$(dirname "$0")" && pwd)
ROOTDIR=$(cd "$SCRIPTDIR/.." && pwd)

set -x

# see also ".mailmap" for how email addresses and names are deduplicated
{
	echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT."
	echo "# This file lists all contributors to the repository."
	echo "# See hack/generate-authors.sh to make modifications."
	echo ""
	git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C sort -uf
} > "$ROOTDIR/AUTHORS"
